### ISSUE TITLE
reST support

### ISSUE THREAD

**Issue by gour** [montylounge/django-mingus#24]
Hello,

I just read http://blog.montylounge.com/2009/sep/24/apps-that-power-django-mingus/ post and under the Django-Markup section it is written "Out of the box Mingus supports (via basic-blog) raw html, markdown, and textile."

Does it mean that there is no reST support in Mingus?

Sincerely,
Gour

p.s. I prefer Mingus over Byteflow hoping xmlrpc will somehow arrive, but reST is 'must'. :-)

**Comment by montylounge** [comment]
The original source of basic-apps-blog only supports markdown. 

I added the support for textile and markdown, and the ability to choose the markup type per post via django-markup.

Basic-apps-inlines and reST don't jive together well and I made the decision to support inlines because I believe it's an interesting app and that, sticking with one of the the concept behind mingus as a learning tool, it would be a good introduction to a reusable app others may find useful.

so because of that decision reST is not supported.

if you would like to add this support please feel free to contribute.

As I begin to merge community development efforts in an attempt to push a 1.0 release of Mingus in the near future, I'll sit down and reconsider the situation above.

For now though - feel free to add reST support to Mingus on your own installation - I believe you just need to add 'resttructredtext;' to the MARKUP_CHOICES  settings.py value django-markup references.

Then as long as you don't try and insert any django-inline xhtml markup into your post... I believe you'll be fine.

I didn't spend too much time with the issue because I don't use markup myself and no one has asked for reST support besides yourself.

Links to note: 
http://docs.mahner.org/django-markup/usage_models.html

http://github.com/montylounge/django-mingus/blob/master/mingus/local_settings.py.template#L53

**Comment by gour** [comment]
Thank you for reply and useful info.

I've to install and test both both Mingus and YaBa and then decide.

**Comment by montylounge** [comment]
Great. yaba is great open source blog as well. best wishes.

**Comment by gour** [comment]
> I didn't spend too much time with the issue because I don't use markup myself and no > one has asked for reST support besides yourself.

I believe that reST support is really becoming important issue along with support for remote publishing and I'm a little bit surprised it's not part of the Django.contrib already and therefore can understand there was no demand for it.

Support for blog-editors like Scribefire (I'd use Emacs) is quite common in PHP arena enabling one to use one's preferred editor to psot instead of fiddling with web-interface.

**Comment by gour** [comment]
Hello!

> For now though - feel free to add reST support to Mingus on your own installation - I > believe you just need to add 'resttructredtext;' to the MARKUP_CHOICES               > settings.py value django-markup references.

I've just tried on test-install (http://gour.webfactional.com/) and it works.

However, usage of reST would mostly benefit along with support for remote publishing, I wrote above.

**Comment by montylounge** [comment]
Gour, I don't think I made it clear - Mingus is a concept project. It's an example on how to leverage reusable apps to deliver what some could argue is a complete blog engine. It's not meant to be the defacto goto blog engine or anything like that. I appreciate your effort in wanting to employ Mingus. But I'm not adding any more features anytime soon. I will be merging changes the community has made to their own forks though. So If you want to use it - awesome. If you don't - totally cool. And if you want to fork it to add feature - feel free!
