### ISSUE TITLE
Error when running 'python setup.py install'

### ISSUE THREAD

**Issue by trent** [montylounge/django-mingus#31]
error: package directory 'mingus/templatetags' does not exist

Looks like this was moved into core but the setup.py was not updated.  Just wanted to let you know of the error I got.

Love Mingus!

**Comment by montylounge** [comment]
doh. yea, i need to resolve that one. thanks for the heads up. almost ready for the final 0.9 release but I need to run through the setup myself from start to finish to make sure it all checks out. cheers!

**Comment by hubbubca** [comment]
I'm itching to get mingus running so I'll anxiously await the .9 release.  I keep getting pip errors etc so I may as well wait until a newer version is released before I report any errors with the install.

**Comment by montylounge** [comment]
Glad to hear you're excited to get going! 

I'm now running mingus 0.9 on blog.montylounge.com without issue. I'm also able to run mingus via the quick start without issue. There are some other users on mingus 0.9 as well. If you are still having issues, please provide further details and I'll do my best to help.

This issue is closed though.
