### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by ericie** [montylounge/django-mingus#5]
Hi I don't know if I'm missing something here. I run a few Django sites but am not an expert Python developer or anything, and I'm not very familiar with virtualenv.

I followed the setup steps until this one
- ./manage.py syncdb

When I got an error. 
ImportError: No module named django.core.management

Generally I look at my PythonPath for that kind of thing, but since the steps to install Mingus are so simple I thought I was missing something, or there was a missing step in the docs.

**Comment by montylounge** [comment]
You need to activate the virtualenv.

So if you have installed virtualenv then you need to do something like this...

source bin/activate

There should be a bin directory in the root of your app.

If you use virtualenvwrapper then it's as simple as saying >> workon [name of your virtualenv]

Let me know if that helps.

But yea, it's not finding django because you haven't activated the virtualenv.

**Comment by ericie** [comment]
Hm that was my first thought too, I had figured out how to use workon already, no dice yet. Thanks for the fast response, I'll keep trying to figure it out, probably it is something basic that I should have learned by now.
